### ISSUE TITLE
What is the replacement for frameScheduledNavigation? 

### ISSUE THREAD

**Issue by sashayakovtseva** [chromedp/cdproto#15]
Hello,

I see that in https://github.com/chromedp/cdproto/commit/8d5e1d04ce19b7b3e61493418de25a281de3709d event frameScheduledNavigation is removed b/c it is deprecated in CDP. However, I am struggling to find out why it is deprecated and what is the analog for it.

Thanks.

**Comment by ZekeLu** [comment]
Please note that it's deprecated by the upstream (https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-frameScheduledNavigation) instead of `chromedp`.

You can use [Page.frameRequestedNavigation](https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-frameRequestedNavigation) instead. Check this commit in 
 which this event is deprecated: https://github.com/chromium/chromium/commit/4005fcf1c724629b63ac6fc390d40a2f8f40be3d

**NOTE**: Any Issue or Pull Request intended for the `cdproto` project should be created over https://github.com/chromedp/pdlgen.

Closing.
